<a href="https://colab.research.google.com/github/ddopazo92/Introduccion_datascience_diego_dopazo/blob/main/clase%2004-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2

# WEB LOREAL
https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo/ch

In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [11]:
links = ['https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo']

for i in range(2,9):
  links.append('https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo?page='+str(i))
len(links)

##Codigo para generar paginas y poder utilizarlas sin tener que copiar una por una

8

In [12]:
links

['https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo',
 'https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo?page=2',
 'https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo?page=3',
 'https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo?page=4',
 'https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo?page=5',
 'https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo?page=6',
 'https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo?page=7',
 'https://salones-es.lorealprofessionnel.com/uy/departamento-de-montevideo?page=8']

In [14]:
direcciones = []
nombres = []

In [15]:
for i in links:
  url = i
  r = requests.get(url)
  soup = BeautifulSoup(r.text, 'html.parser')
  for j in soup.find_all('span',class_="lf-location-default__content__container__header__title__text lf-geo-divisions__top__wrapper__main__locations__list__location__content__container__header__title__text"):
        nombres.append(j.text)
  for k in soup.find_all('span',class_="lf-parts-address__content__street lf-location-default__content__container__address__content__street lf-geo-divisions__top__wrapper__main__locations__list__location__content__container__address__content__street"):
        direcciones.append(k.text)

In [ ]:
soup

In [17]:
direcciones

['SOLANO GARCIA 2541',
 'ACEVEDO DIAZ 1679 esq COLONIA',
 'MANUEL PAGOLA 3309',
 'AV ITALIA 6429',
 '26 MARZO 3349',
 'GERMÁN BARBATO 1360',
 'CNO MALDONADO 6785',
 'FERNANDEZ CRESPO 2075 ESQ NUEVA YORK',
 'AV SARMIENTO 2682',
 'MARIA STAGNERO DE MUNAR 2543',
 'ELLAURI 868',
 'AGRACIADA 3690',
 'AV DEL LIBERTADOR 1804',
 'GUAYAQUI 3291',
 'LUIS A DE HERRERA 2220 BIS',
 'AV RIVERA 2901 Esq LAMAS',
 'JOAQUIN REQUENA 1617',
 'EJIDO 1369',
 'JUAN PAULLIER 1961',
 'CONVENCION 1434',
 'GRECIA 3406',
 'YARO 862',
 'AV GRAL MARIA PAZ 1470',
 'EJIDO 1369',
 'JOSÉ MARTI 3338',
 'CONVENCION 1434',
 'GUIPUZCOA 404',
 'AGRACIADA 2784 Loc 003',
 'VAZQUEZ LEDESMA 2893',
 'ROSTAND 1571',
 'FCO. SIMON 2284 ESQ. VELAZCO',
 'HAVEN PUNTA CARRETAS SHOPPING',
 'JUAN SPIKERMAN 2052',
 '18 DE JULIO 1182',
 'CORCEGA 1995',
 '18 DE JULIO 2067',
 'ORINOCO 5010',
 'PEDRO OLMIDA 2725',
 'GRAL. FLORES 3350',
 '21 DE SETIEMBRE 2884',
 'AV ITALIA 6945 BIS',
 'SAN JOSE 835',
 'AROCENA 1571',
 'RIO NEGRO 1311',
 'CHUCARRO 1156',
 'HOQUART 2075',
 'ZUM FELDE 2193',
 'JOSE L. TERRA 2220 LOCAL 93',
 'GUAYAQUI 2952',
 'VAZQUEZ 1424',
 'GRECIA 3373 BIS',
 'AROCENA 1695 BIS',
 'DR PABLO DE MARIA 1574',
 'GABRIEL PEREIRA 3185 BIS',
 'SOCA 1291',
 'DR ALFREDO NAVARRO 3152',
 'AV RIVERA 2584',
 'AV BRASIL 2923',
 'GUARDIA ORIENTAL 3004',
 'AROCENA 1652',
 'GUAYAQUI 3376 BIS',
 'HERRERO Y ESPINOSA 1461 ESQ. NELSON',
 'MASSINI 3342',
 '18 DE JULIO 2007',
 'JOANICO 3332',
 'VAZQUEZ LEDESMA 2869 BIS',
 'ALBERDI 6549',
 'AV GRAL MARIA PAZ 1470',
 'PLACIDO ELLAURI 3470',
 'MARIO CASSINONI 1085',
 'JUAN PAULLIER 1293',
 'GRAL URQUIZA 2589',
 'JOSÉ MARTI 3338',
 'SARMIENTO 2640',
 'TREINTA Y TRES 1384',
 'AV ITALIA 7520',
 'Alfredo Arocena 1980b',
 'JAIME ZUDAÑEZ 2716',
 'JUAN SPIKERMAN 2052',
 'CONSTITUYENTE 1694',
 'SARANDI 686',
 'SAN MARTIN 2194',
 'JUAN BENITO BLANCO 1190',
 'AV BRASIL 2538',
 'MARIO CASSINONI 1085',
 '8 DE OCTUBRE 3329',
 '8 DE OCTUBRE 2981 AP 401',
 'JUAN PAULLIER 1293',
 'FRANCISCO SOCA 1313',
 'AV DEL LIBERTADOR 1680 LOCAL 2',
 'AV DR SANTIN CARLOS ROSSI 4323',
 'RIO NEGRO 1246',
 'Av Gral Rivera 3600',
 'AGRACIADA 3923',
 'CEBOLLATI 1489',
 'GABRIEL PEREIRA 3084 LOC 1001',
 'MILLAN 3729',
 '21 de Setiembre 2867',
 'LUIS A. DE HERRERA 3302',
 'COLONIA 1578',
 'CONSTITUYENTE 1694',
 'GUAYABO 1700',
 'AUSTRIA 1847',
 'COLONIA 1492',
 'DR. ENRIQUE POUEY 2446',
 'SARANDI 511',
 'AV. SARMIENTO 2384',
 'AGRACIADA 3599',
 'BURICAYUPI  3052',
 'RIO NEGRO 1311',
 'BVAR ESPAÑA 2669',
 'SAN MARTÍN 3389',
 'AV BRASIL 2817',
 'ALBERDI 6599 BIS',
 '26 DE MARZO 3456',
 'FRANCISCO VIDAL 758',
 'EDUARDO VICTOR HAEDO 2288 LOC 1',
 'MONTEVIDEO SHOPPING 2DO NIVEL',
 'MANUEL PAGOLA 3114',
 'NUEVOCENTRO SHOPPING',
 'DR. ENRIQUE POUEY 2446',
 'SARANDI 511',
 '21 DE SETIEMBRE 2884',
 'AGRACIADA 3599',
 'PORTONES SHOPPING LOCAL S 44',
 'RIVERA 3453',
 'SAN JOSE 835',
 'RIO NEGRO 1311',
 'AV DE LAS INSTRUCCIONES 776',
 'AV BRASIL 2422',
 'SOCA 1247',
 '21 DE SETIEMBRE 2667',
 'JOSE L. TERRA 2220 LOCAL 93',
 'GUAYAQUI 2952',
 'LUIS CAVIA 2638',
 'SAN JOSE 964',
 'LUIS A. DE HERRERA 3171',
 'SORIANO\xa0879',
 'AV RIVERA 6098',
 'SARANDI 443',
 'AGRACIADA 3690',
 'AV DEL LIBERTADOR 1804',
 'AV RIVERA 2901 Esq LAMAS',
 'ALBERDI 6549',
 'PLACIDO ELLAURI 3470',
 'JOSE MARMOL 288',
 'GRAL URQUIZA 2589',
 'AV BOLIVIA 2092',
 'SARMIENTO 2640',
 'TREINTA Y TRES 1384',
 'AGRACIADA 3885',
 'CARLOS SAEZ 6415',
 '26 DE MARZO 1280',
 'LUIS ALBERTO DE HERRERA 2612',
 'GABRIEL PEREIRA 2940/A',
 'Alfredo Arocena 1980b',
 'MILLAN 3811',
 'CARLOS SAEZ 6415',
 'BESNES E IRIGOYEN 5675 BIS',
 'VÁZQUEZ 1385']

In [18]:
nombres

['SILVIA PIAF INTERNACIONAL',
 'ELSA ESTILISTA',
 'MARLENE COIFFEUR',
 'GABRIELA RENEE DEL POZZO',
 'TRENDS',
 'ELIZARDO',
 'JOSE VILLAR COIFFEUR',
 'DIEGO ALFONSO',
 'SERENDIPITY',
 'COQUETAS',
 'ESTILO M',
 'ROMANTIQUE',
 'MUY BONITA',
 'BLU PELUQUERIA',
 'VL SALON DE BELLEZA',
 "DUFFEY'S HAIRSTYLE",
 'STYLE BY CLAU R',
 'FOREVER SUMMER',
 'CLAUDIA BARBOZA DUARTE',
 'PELUQUERIA KALA S',
 'PEINADOS SUSANA',
 'SUAND PELUQUERIA',
 'PAUSE SPA',
 'FOREVER SUMMER',
 'MARIANA BELLO',
 'PELUQUERIA KALA S',
 'CASIANA',
 'SALON MAGNOLIA NAILS Y BEAUTY',
 'OLGA STYLING EXPERT',
 'UTOPIA CARRASCO',
 'EBEN EZER',
 'CONCEPTO OM',
 'PEINADOS RUTH',
 'ABRIL',
 'M Y D',
 'JOSEFINA PEINADOS',
 'COAGE',
 'PEINADOS LAWCOR',
 'NEREY',
 'PERFIL HAIR',
 'CECILIA PAIS',
 'ESTILO Y ARTE',
 'CARINA AZAMBUYA',
 'NUEVO ESTILO',
 'NEGRA MARÍA',
 'VIOLET',
 'S G B',
 'SIMONAS',
 'PELUQUERIA ALEJANDRO MONTEIRO',
 'SU ESTILO',
 'GENNESIS',
 'SILVANA DENICOLA',
 'MACHADO NAUAR',
 'TU STYLO',
 'ESTILO RAICES',
 'FLORENCIA PEINADOS',
 'VICKY OLIVERA PELUQUERIA DE DISEÑO',
 'CORE´S STYLIST',
 'PUNTONOVIA',
 'NI UN PELO DE TONTA',
 'WI DESIGN',
 'DANIEL PEREIRA',
 'GUSTAVO TITO',
 'ESPACIO 18',
 'KEF CENTRO ESTETICO',
 'VERO LAFFITTE PELUQUERIA',
 'MOSS HAIR STYLING',
 'PAUSE SPA',
 "L'ESSENCE",
 'MUY MAJO',
 'LEITMOTIV',
 'CENTRO ESTETICO SANDRA SILVA',
 'MARIANA BELLO',
 'LOOK Y ARTE',
 'F. SILVA STAFF',
 'LAS ESCARDO',
 'CONCEPTO OM',
 'JEAN PERALTA',
 'PEINADOS RUTH',
 'EVASION',
 'AZUL DESING',
 'MUBAREK HAIR BOUTIQUE',
 'ANA S',
 'ALEJANDRO RIVERO',
 'MUY MAJO',
 'AMO MI ESTILO',
 'MARYALISADOS',
 'LEITMOTIV',
 'AMOR MIO',
 'MISS ELIZABETH',
 'MONA LISCI',
 'MERAKI PELUQUERIA DE DISEÑO',
 'EUCLIDES',
 'JEAN PIERRE',
 'GARDENIA',
 'BONTI HAIR DESING',
 'VALENTINA CABALLERO',
 'CONCEPTO OM',
 'INSTITUTO DE BELLEZA MARIANA',
 'SHAMPOO PEINADOS',
 'EVASION',
 'PEINADOS PRESTIGE',
 'BR ESTILISTA',
 'SHOPPING DEL ESTILO',
 'FEMINAS',
 'VISAGE',
 'JOAQUINA PEINADOS',
 'ANDREA HUERTA',
 'MIGUEL BELHOT',
 'NUEVO ESTILO',
 'BENDITO',
 'CELY ESTETICA INTEGRAL',
 'CAYETANA',
 'MARTHA ESTILISTA',
 'DR. HAIR',
 'AZZIA BEAUTY',
 'GIANELLA PIUMA ESTILISTA',
 'LECANAT',
 'ENIGMA',
 'URBAN CUT',
 'FEMINAS',
 'VISAGE',
 'PERFIL HAIR',
 'ANDREA HUERTA',
 'Y HAIR STYLIST',
 'D DIVINAS',
 'ESTILO Y ARTE',
 'NUEVO ESTILO',
 'ANDRES MACHIN',
 'CUTTING EDGE',
 'MATISSE',
 'CLABELL',
 'SIMONAS',
 'PELUQUERIA ALEJANDRO MONTEIRO',
 'MIL RIZOS BY GISEL PACHECO',
 "L'EQUIPE",
 'MIRIAM K',
 'ENRIQUE COIFFEUR',
 'NIVEL 1',
 'INNOVA',
 'ROMANTIQUE',
 'MUY BONITA',
 "DUFFEY'S HAIRSTYLE",
 'MOSS HAIR STYLING',
 "L'ESSENCE",
 'COQUETERIAS',
 'CENTRO ESTETICO SANDRA SILVA',
 'VIRAGO STUDIO',
 'LOOK Y ARTE',
 'F. SILVA STAFF',
 'KADIM ESTETICA INTEGRAL',
 'LA PELUQUERIA',
 'ESTILO MIA',
 'PAULA ALVAREZ CENTRO ESTETICO',
 'COLVERA CABALLERO ANDREA CECILIA',
 'CONCEPTO OM',
 'HEBER INTERCOIFFURE',
 'LA PELUQUERIA',
 'STAFF MARIO COIFFEURS',
 'AMBAR']

In [19]:
dic = {'Nombre':nombres,'Direccion':direcciones}
df = pd.DataFrame(dic)
df

                        Nombre                      Direccion
0    SILVIA PIAF INTERNACIONAL             SOLANO GARCIA 2541
1               ELSA ESTILISTA  ACEVEDO DIAZ 1679 esq COLONIA
2             MARLENE COIFFEUR             MANUEL PAGOLA 3309
3     GABRIELA RENEE DEL POZZO                 AV ITALIA 6429
4                       TRENDS                  26 MARZO 3349
..                         ...                            ...
155                CONCEPTO OM          Alfredo Arocena 1980b
156        HEBER INTERCOIFFURE                    MILLAN 3811
157              LA PELUQUERIA               CARLOS SAEZ 6415
158      STAFF MARIO COIFFEURS     BESNES E IRIGOYEN 5675 BIS
159                      AMBAR                   VÁZQUEZ 1385

[160 rows x 2 columns]

In [20]:
url = 'https://raw.githubusercontent.com/bttmly/nba/master/data/teams.json'

In [21]:
df = pd.read_json(url)
df

,teamId,abbreviation,teamName,simpleName,location
0,1610612737,ATL,Atlanta Hawks,Hawks,Atlanta
1,1610612738,BOS,Boston Celtics,Celtics,Boston
2,1610612751,BKN,Brooklyn Nets,Nets,Brooklyn
3,1610612766,CHA,Charlotte Hornets,Hornets,Charlotte
4,1610612741,CHI,Chicago Bulls,Bulls,Chicago
5,1610612739,CLE,Cleveland Cavaliers,Cavaliers,Cleveland
6,1610612742,DAL,Dallas Mavericks,Mavericks,Dallas
7,1610612743,DEN,Denver Nuggets,Nuggets,Denver
8,1610612765,DET,Detroit Pistons,Pistons,Detroit
9,1610612744,GSW,Golden State Warriors,Warriors,Golden State
10,1610612745,HOU,Houston Rockets,Rockets,Houston
11,1610612754,IND,Indiana Pacers,Pacers,Indiana
12,1610612746,LAC,Los Angeles Clippers,Clippers,Los Angeles
13,1610612747,LAL,Los Angeles Lakers,Lakers,Los Angeles
14,1610612763,MEM,Memphis Grizzlies,Grizzlies,Memphis
15,1610612748,MIA,Miami Heat,Heat,Miami
16,1610612749,MIL,Milwaukee Bucks,Bucks,Milwaukee
17,1610612750,MIN,Minnesota Timberwolves,Timberwolves,Minnesota
18,1610612740,NOP,New Orleans Pelicans,Pelicans,New Orleans
19,1610612752,NYK,New York Knicks,Knicks,New York
20,1610612760,OKC,Oklahoma City Thunder,Thunder,Oklahoma City
21,1610612753,ORL,Orlando Magic,Magic,Orlando
22,1610612755,PHI,Philadelphia 76ers,76ers,Philadelphia
23,1610612756,PHX,Phoenix Suns,Suns,Phoenix
24,1610612757,POR,Portland Trail Blazers,Trail Blazers,Portland
25,1610612758,SAC,Sacramento Kings,Kings,Sacramento
26,1610612759,SAS,San Antonio Spurs,Spurs,San Antonio
27,1610612761,TOR,Toronto Raptors,Raptors,Toronto
28,1610612762,UTA,Utah Jazz,Jazz,Utah
29,1610612764,WAS,Washington Wizards,Wizards,Washington